-- ============================================================
-- ReturnDesk Database Schema
-- Run via: node scripts/setup-db.js
-- ============================================================

-- Enum: status lifecycle
CREATE TYPE request_status AS ENUM (
  'Open',
  'In Review',
  'Approved',
  'Rejected',
  'Completed'
);

-- Enum: reason for return
CREATE TYPE return_reason AS ENUM (
  'Damaged',
  'Wrong Item',
  'Size Issue',
  'Not As Described',
  'Changed Mind'
);

-- Enum: resolution outcome (set only when Approved)
CREATE TYPE resolution_type AS ENUM (
  'Refund',
  'Replacement',
  'Store Credit'
);

-- Sequence for human-readable references: RD-000001, RD-000002, ...
-- Atomic: no race condition unlike count(*)+1
CREATE SEQUENCE IF NOT EXISTS request_ref_seq START 1;

-- ============================================================
-- Main table: return_requests
-- ============================================================
CREATE TABLE IF NOT EXISTS return_requests (
  id              UUID            PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Auto-generated by the database on insert. Agents never type this.
  reference       VARCHAR(12)     UNIQUE NOT NULL,

  -- Customer info (locked once decided)
  customer_name   VARCHAR(255)    NOT NULL,
  customer_email  VARCHAR(255)    NOT NULL,

  -- Order and item info (locked once decided)
  order_id        VARCHAR(100)    NOT NULL,
  item_name       VARCHAR(255)    NOT NULL,
  item_sku        VARCHAR(100),
  quantity        INTEGER         NOT NULL CHECK (quantity >= 1),

  -- Classification
  reason          return_reason   NOT NULL,
  status          request_status  NOT NULL DEFAULT 'Open',

  -- Resolution: only populated when status = Approved
  -- If resolution = Refund, refund_amount must be > 0
  -- If resolution = Replacement or Store Credit, refund_amount must be null
  resolution      resolution_type,
  refund_amount   NUMERIC(10, 2),

  -- Soft delete: record stays in DB, just disappears from active lists
  is_removed      BOOLEAN         NOT NULL DEFAULT FALSE,
  removed_at      TIMESTAMPTZ,

  created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- ============================================================
-- Business Rule 3: One live request per (order_id, item_name)
--
-- This partial unique index enforces it at the database level.
-- "Live" means: not Rejected, not Completed, not removed.
-- When a request is closed (Rejected/Completed) or removed,
-- it falls OUT of this index — allowing a new request to be created.
-- ============================================================
CREATE UNIQUE INDEX IF NOT EXISTS unique_active_item_request
  ON return_requests (order_id, item_name)
  WHERE status NOT IN ('Rejected', 'Completed')
    AND is_removed = FALSE;

-- Indexes for list query performance (partial: only active records)
CREATE INDEX IF NOT EXISTS idx_requests_status
  ON return_requests (status)
  WHERE is_removed = FALSE;

CREATE INDEX IF NOT EXISTS idx_requests_reason
  ON return_requests (reason)
  WHERE is_removed = FALSE;

CREATE INDEX IF NOT EXISTS idx_requests_created_at
  ON return_requests (created_at DESC)
  WHERE is_removed = FALSE;

CREATE INDEX IF NOT EXISTS idx_requests_updated_at
  ON return_requests (updated_at DESC)
  WHERE is_removed = FALSE;

CREATE INDEX IF NOT EXISTS idx_requests_order_id
  ON return_requests (order_id)
  WHERE is_removed = FALSE;

-- ============================================================
-- Notes table: append-only, never edited or deleted
-- ============================================================
CREATE TABLE IF NOT EXISTS notes (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  request_id  UUID        NOT NULL REFERENCES return_requests(id),
  content     TEXT        NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for fetching all notes of a request efficiently
CREATE INDEX IF NOT EXISTS idx_notes_request_id
  ON notes (request_id);
