/**
 * queries/requests.js — Data access layer.
 *
 * Contains only raw SQL queries. No business logic lives here.
 * Every function accepts plain values and returns plain JS objects.
 * Business rules are enforced in services/requests.js.
 */

const pool = require('../db/pool');

// ─────────────────────────────────────────────
// CREATE
// ─────────────────────────────────────────────

/**
 * Insert a new return request.
 * Reference is auto-generated by the database using the request_ref_seq sequence.
 */
async function insertRequest({ customer_name, customer_email, order_id, item_name, item_sku, quantity, reason }) {
  const result = await pool.query(
    `INSERT INTO return_requests
       (reference, customer_name, customer_email, order_id, item_name, item_sku, quantity, reason)
     VALUES
       ('RD-' || LPAD(nextval('request_ref_seq')::text, 6, '0'),
        $1, $2, $3, $4, $5, $6, $7)
     RETURNING *`,
    [customer_name, customer_email, order_id, item_name, item_sku ?? null, quantity, reason]
  );
  return result.rows[0];
}

// ─────────────────────────────────────────────
// READ
// ─────────────────────────────────────────────

/**
 * List requests with optional search, status/reason filter, sort, and pagination.
 * All filtering and sorting happens in SQL — never in JavaScript.
 *
 * Security note: sortBy and sortOrder are validated against an allowlist by Zod
 * before reaching this function, so interpolating them directly is safe.
 */
async function findRequests({ search, status, reason, sortBy, sortOrder, page, limit }) {
  // Defensive defaults — Zod should provide these, but guard anyway
  const safeSortBy = sortBy || 'created_at';
  const safeSortOrder = (sortOrder || 'desc').toUpperCase();
  const safePage = page || 1;
  const safeLimit = limit || 20;
  const offset = (safePage - 1) * safeLimit;
  const conditions = ['is_removed = FALSE'];
  const params = [];

  // Text search across customer name, order ID, and reference
  if (search) {
    params.push(`%${search}%`);
    const idx = params.length;
    conditions.push(
      `(customer_name ILIKE $${idx} OR order_id ILIKE $${idx} OR reference ILIKE $${idx})`
    );
  }

  if (status) {
    params.push(status);
    conditions.push(`status = $${params.length}::request_status`);
  }

  if (reason) {
    params.push(reason);
    conditions.push(`reason = $${params.length}::return_reason`);
  }

  const whereClause = `WHERE ${conditions.join(' AND ')}`;
  // sortBy/sortOrder are allowlisted by Zod — no SQL injection risk.
  // id is appended as a stable tiebreaker so pagination is deterministic
  // when two rows share the same value for the primary sort column (e.g. seeded data).
  const orderClause = `ORDER BY ${safeSortBy} ${safeSortOrder}, id ASC`;

  // Run count and data queries. Count uses the same WHERE params.
  const countResult = await pool.query(
    `SELECT COUNT(*) FROM return_requests ${whereClause}`,
    params
  );
  const total = parseInt(countResult.rows[0].count, 10);

  // Add pagination params after the count query (so count doesn't use them)
  params.push(safeLimit, offset);
  const dataResult = await pool.query(
    `SELECT * FROM return_requests
     ${whereClause}
     ${orderClause}
     LIMIT $${params.length - 1} OFFSET $${params.length}`,
    params
  );

  return { rows: dataResult.rows, total };
}

/**
 * Find a single non-removed request by ID.
 * Returns null if not found or if removed (callers convert to 404).
 */
async function findRequestById(id) {
  const result = await pool.query(
    `SELECT * FROM return_requests WHERE id = $1 AND is_removed = FALSE`,
    [id]
  );
  return result.rows[0] ?? null;
}

/**
 * Find all notes for a request in chronological order (oldest first).
 */
async function findNotesByRequestId(requestId) {
  const result = await pool.query(
    `SELECT * FROM notes WHERE request_id = $1 ORDER BY created_at ASC`,
    [requestId]
  );
  return result.rows;
}

/**
 * Check if an active (live) request already exists for a given (order_id, item_name).
 * Used to enforce Business Rule 3 at the application level before the DB rejects it.
 * excludeId lets update operations exclude the current record from the check.
 */
async function findActiveRequestForItem(orderId, itemName, excludeId = null) {
  // Only active requests participate in the duplicate check.
  // Rejected and Completed requests are considered closed.
  let query = `
    SELECT id FROM return_requests
    WHERE order_id = $1
      AND item_name = $2
      AND status NOT IN ('Rejected', 'Completed')
      AND is_removed = FALSE
  `;
  const params = [orderId, itemName];

  if (excludeId) {
    params.push(excludeId);
    query += ` AND id != $${params.length}`;
  }

  const result = await pool.query(query, params);
  return result.rows[0] ?? null;
}

// ─────────────────────────────────────────────
// UPDATE
// ─────────────────────────────────────────────

/**
 * Update editable detail fields of a request.
 * Only updates fields that are explicitly provided (partial update).
 */
async function updateRequest(id, fields) {
  const allowed = ['customer_name', 'customer_email', 'order_id', 'item_name', 'item_sku', 'quantity', 'reason'];
  const setClauses = [];
  const params = [];

  for (const key of allowed) {
    if (key in fields) {
      params.push(fields[key]);
      setClauses.push(`${key} = $${params.length}`);
    }
  }

  setClauses.push('updated_at = NOW()');
  params.push(id);

  const result = await pool.query(
    `UPDATE return_requests
     SET ${setClauses.join(', ')}
     WHERE id = $${params.length} AND is_removed = FALSE
     RETURNING *`,
    params
  );
  return result.rows[0] ?? null;
}

/**
 * Update status (and optionally resolution/refund_amount).
 * resolution and refund_amount are always explicitly passed (null clears them).
 */
async function updateStatus(id, status, resolution, refundAmount) {
  const result = await pool.query(
    `UPDATE return_requests
     SET status = $2::request_status,
         resolution = $3::resolution_type,
         refund_amount = $4,
         updated_at = NOW()
     WHERE id = $1 AND is_removed = FALSE
     RETURNING *`,
    [id, status, resolution ?? null, refundAmount ?? null]
  );
  return result.rows[0] ?? null;
}

/**
 * Soft-delete a request: set is_removed = true and record the timestamp.
 * The row stays in the database forever.
 */
async function softDeleteRequest(id) {
  const result = await pool.query(
    `UPDATE return_requests
     SET is_removed = TRUE,
         removed_at = NOW(),
         updated_at = NOW()
     WHERE id = $1 AND is_removed = FALSE
     RETURNING *`,
    [id]
  );
  return result.rows[0] ?? null;
}

// ─────────────────────────────────────────────
// NOTES
// ─────────────────────────────────────────────

/**
 * Insert a new note. Notes are append-only — no update or delete queries exist.
 */
async function insertNote(requestId, content) {
  const result = await pool.query(
    `INSERT INTO notes (request_id, content) VALUES ($1, $2) RETURNING *`,
    [requestId, content]
  );
  return result.rows[0];
}

module.exports = {
  insertRequest,
  findRequests,
  findRequestById,
  findNotesByRequestId,
  findActiveRequestForItem,
  updateRequest,
  updateStatus,
  softDeleteRequest,
  insertNote,
};
